"""Email sender module for Painhunter reports."""

import os
import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from typing import List, Dict
from datetime import datetime


# Email HTML template
HTML_TEMPLATE = """
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <style>
        body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; line-height: 1.6; color: #333; max-width: 800px; margin: 0 auto; padding: 20px; }}
        h1 {{ color: #2563eb; border-bottom: 2px solid #e5e7eb; padding-bottom: 10px; }}
        h2 {{ color: #1e40af; margin-top: 30px; }}
        .opportunity {{ background: #f8fafc; border-radius: 8px; padding: 20px; margin: 15px 0; border-left: 4px solid #3b82f6; }}
        .score {{ display: inline-block; background: #dbeafe; color: #1e40af; padding: 2px 8px; border-radius: 4px; font-weight: bold; }}
        .mvp {{ background: #ecfdf5; padding: 10px 15px; border-radius: 6px; margin: 5px 0; color: #065f46; }}
        .meta {{ color: #6b7280; font-size: 14px; margin-bottom: 10px; }}
        .footer {{ margin-top: 40px; padding-top: 20px; border-top: 1px solid #e5e7eb; color: #9ca3af; font-size: 12px; }}
    </style>
</head>
<body>
    <h1>🎯 Painhunter Daily Report</h1>
    <p class="meta">{date} | Found {count} business opportunities</p>

    <p>Here's what users are struggling with today:</p>

    {content}

    <div class="footer">
        <p>Generated by Painhunter - Reddit Pain Point Hunter</p>
        <p>Source: r/SaaS, r/Entrepreneur | Past 24 hours</p>
    </div>
</body>
</html>
"""


OPPORTUNITY_TEMPLATE = """
    <div class="opportunity">
        <h2>💡 {pain_point}</h2>
        <p class="meta">Target Audience: {audience}</p>
        <p><span class="score">Business Value: {score}/5</span></p>
        <h3>MVP Suggestions:</h3>
        {mvp_list}
        <p class="meta" style="margin-top: 15px;">Source: {sources}</p>
    </div>
"""


def format_opportunities_html(opportunities: List[Dict]) -> str:
    """Format opportunities into HTML."""
    if not opportunities:
        return "<p>No opportunities found today.</p>"

    html_parts = []
    for opp in opportunities:
        mvp_html = "".join(
            f'<div class="mvp">• {idea}</div>' for idea in opp.get("mvp_suggestions", [])
        )
        sources = ", ".join(opp.get("source_posts", [])[:3])

        html_parts.append(
            OPPORTUNITY_TEMPLATE.format(
                pain_point=opp.get("pain_point", "N/A"),
                audience=opp.get("target_audience", "N/A"),
                score=opp.get("business_value_score", 0),
                mvp_list=mvp_html,
                sources=sources,
            )
        )

    return "".join(html_parts)


def generate_html_report(analysis: Dict) -> str:
    """Generate complete HTML email report."""
    opportunities = analysis.get("opportunities", [])
    content = format_opportunities_html(opportunities)

    return HTML_TEMPLATE.format(
        date=datetime.now().strftime("%Y-%m-%d"),
        count=len(opportunities),
        content=content,
    )


def send_email(
    smtp_host: str,
    smtp_port: int,
    username: str,
    password: str,
    to_emails: List[str],
    subject: str = None,
    html_body: str = None,
) -> bool:
    """Send email via SMTP.

    Args:
        smtp_host: SMTP server hostname
        smtp_port: SMTP port (usually 587 for TLS)
        username: SMTP login username (usually email address)
        password: SMTP password or app token
        to_emails: List of recipient email addresses
        subject: Email subject (auto-generated if None)
        html_body: HTML content (required)

    Returns:
        True if sent successfully, False otherwise
    """
    if not html_body:
        print("Error: No HTML body provided")
        return False

    # Default subject with date
    if subject is None:
        date_str = datetime.now().strftime("%Y-%m-%d")
        subject = f"🎯 Painhunter Daily Report - {date_str}"

    # Create message
    msg = MIMEMultipart("alternative")
    msg["Subject"] = subject
    msg["From"] = username
    msg["To"] = ", ".join(to_emails)

    # Attach HTML
    html_part = MIMEText(html_body, "html")
    msg.attach(html_part)

    try:
        # Connect and send
        with smtplib.SMTP(smtp_host, smtp_port) as server:
            server.starttls()
            server.login(username, password)
            server.sendmail(username, to_emails, msg.as_string())

        print(f"Email sent successfully to {len(to_emails)} recipients")
        return True
    except Exception as e:
        print(f"Error sending email: {e}")
        return False


def send_report(
    analysis: Dict,
    smtp_host: str = None,
    smtp_port: int = 587,
    username: str = None,
    password: str = None,
    to_emails: List[str] = None,
) -> bool:
    """Generate and send the daily report via email.

    Reads SMTP settings from environment if not provided.
    """
    # Get settings from environment
    smtp_host = smtp_host or os.environ.get("SMTP_HOST")
    smtp_port = smtp_port or int(os.environ.get("SMTP_PORT", 587))
    username = username or os.environ.get("SMTP_USERNAME")
    password = password or os.environ.get("SMTP_PASSWORD")

    to_emails = to_emails or os.environ.get("TO_EMAILS", "").split(",")

    # Validate required settings
    if not all([smtp_host, username, password, to_emails]):
        missing = []
        if not smtp_host: missing.append("SMTP_HOST")
        if not username: missing.append("SMTP_USERNAME")
        if not password: missing.append("SMTP_PASSWORD")
        if not to_emails or not to_emails[0]: missing.append("TO_EMAILS")
        print(f"Warning: Missing email settings: {', '.join(missing)}")
        print("Set these in .env or environment variables")
        return False

    # Generate HTML report
    html_body = generate_html_report(analysis)

    # Send email
    return send_email(
        smtp_host=smtp_host,
        smtp_port=smtp_port,
        username=username,
        password=password,
        to_emails=[e.strip() for e in to_emails if e.strip()],
        html_body=html_body,
    )


if __name__ == "__main__":
    # Test email generation
    test_analysis = {
        "opportunities": [
            {
                "pain_point": "Small businesses struggle to find affordable SaaS tools",
                "target_audience": "Small business owners with limited budgets",
                "business_value_score": 4,
                "mvp_suggestions": [
                    "Curated directory of free/affordable alternatives",
                    "AI-powered tool recommendation engine"
                ],
                "source_posts": ["Post 1", "Post 2"]
            }
        ]
    }

    print("Testing HTML report generation...")
    html = generate_html_report(test_analysis)
    print(f"Generated {len(html)} characters of HTML")

    # Save to file for preview
    with open("/tmp/test_report.html", "w") as f:
        f.write(html)
    print("Preview saved to /tmp/test_report.html")
